security:
    encoders:
        Sergey\TestBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        users:
            entity:
                class: SergeyTestBundle:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

        secured_area:
              pattern:    ^/
              oauth:
                  resource_owners:
                      facebook:      /login_facebook
                  login_path:        /login
                  failure_path:      /login
                  oauth_user_provider:
                      service: sergey.test_bundle.provider.facebook

              # Turn on anonymous for testings need.
              anonymous: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
