security:
    providers:
        users:
            entity:
                class: SergeyTestBundle:User
                property: email

    firewalls:
        secured_area:
            pattern:    ^/
            oauth:
                resource_owners:
                    facebook:      /login_facebook
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: sergey.test_bundle.provider.facebook

            # Turn on anonymous for testings need.
            anonymous: ~

            logout:
                path: logout
                target: home
                invalidate_session: true
                delete_cookies:
                    PHPSESSID: { path: '/', domain: ~ }

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/media', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/im&, roles: ROLE_USER }
